/*
 * Common.hpp
 *
 *  Created on: Nov 27, 2013
 *      Author: cfyz
 */

#ifndef COMMON_HPP_
#define COMMON_HPP_

#include "BearLibTerminal.h"
#include <stdint.h>
#include <sstream>

uint64_t GetTime();

void delay(int ms);

template<typename T> std::string to_string(const T& value)
{
	std::ostringstream ss;
	ss << value;
	return ss.str();
}

void TestBasicOutput();
void TestDefaultFont();
void TestTilesets();
void TestSprites();
void TestManualCellsize();
void TestAutoGenerated();
void TestMultipleFonts();
void TestFontViewer();
void TestLayers();
void TestExtendedBasics();
void TestExtendedInterlayer();
void TestExtendedSmoothScroll();
void TestDynamicSprites();
void TestSynchronousRender();
void TestKeyboard();
void TestMouse();
void TestTextInput();

#endif /* COMMON_HPP_ */
