/*
 * Common.hpp
 *
 *  Created on: Nov 27, 2013
 *      Author: cfyz
 */

#ifndef COMMON_HPP_
#define COMMON_HPP_

#include "BearLibTerminal.h"

void TestBasicOutput();
void TestDefaultFont();
void TestTilesets();
void TestSprites();
void TestManualCellsize();
void TestAutoGenerated();
void TestFontViewer();
void TestKeyboard();

#endif /* COMMON_HPP_ */
